# Setup
title: Yatian Liu
description: >- # this means to ignore newlines until "baseurl:"
  A website about Yatian Liu and his research experiences.
baseurl: "/"

plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
    values:
      author: "Yatian Liu"

# Custom vars

github:
  repo: https://github.com/yatian-liu/yatian-liu.github.io

exclude:
  # Default
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # Additional exclusion
  - .vscode/
