# Setup
title: Yatian Liu
description: > # Treat newlines as spaces in the following block
  A website about Yatian Liu and his research experiences.

plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
    values:
      author: "Yatian Liu"

# Custom vars

github:
  repo: https://github.com/yatian-liu/yatian-liu.github.io

google_analytics_id: G-P0PRXE8CHX

exclude:
  # Default
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # Additional exclusion
  - .vscode/
