# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Yatian Liu
email:            dougliu@umich.edu
# tagline:          'A Jekyll theme'
description:      >- # this means to ignore newlines until "url:"
  A website about Yatian Liu as a person and his research experiences.
url:              ""
baseurl:          /

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/yatian-liu/yatian-liu.github.io

exclude:
  # Default
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # Additional exclusion
  - .vscode/
